name: .NET 5

on:
  push:
    branches: [ main, HW3 ]
  pull_request:
    branches: [ main, HW3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore OilTycoon/OilTycoon.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore OilTycoon/OilTycoon.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal OilTycoon/OilTycoon.sln
 
